name: "Gilda Local HA add-on"
version: "1.7.2"
slug: "gilda-local"
description: "Gilda Local addon. Provides the Gilda local server"
url: "https://github.com/marcelomatus/gilda-add-on/gilda-local"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7

ports:
  5024/tcp: 5024

homeassistant_api: true
hassio_api: true
auth_api: true
