name: "Gilda Opts HA add-on"
version: "1.2.0"
slug: "gilda-local"
description: "Gilda Local addon. Provides the Gilda local server"
url: "https://github.com/marcelomatus/gilda-add-on"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7

ports:
  6012/tcp: 6012

