name: "Gilda Opts HA add-on"
description: "Gilda Opts HA add-on. Implements an EMS in HA."
url: "https://github.com/marcelomatus/gilda-add-on"
version: "1.2.0"
slug: "gilda"
init: false
arch:
  - aarch64
  - amd64
  - i386

ports:
  5012/tcp: 5012
