name: "Gilda Opts HA add-on"
version: "1.2.0"
slug: "gilda"
description: "Gilda Opts addon. Provides the Gilda optimizer server"
url: "https://github.com/marcelomatus/gilda-add-on"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7

ports:
  5012/tcp: 5012

